#ifndef GLOBALS_H
#define GLOBALS_H

#include <QMap>
#include <QString>
#include <Qt>

struct FallbackValues {
  QString icon = "solidwriting_icon.ico";
  QString fontFamily = "Segoe UI";
  int fontSize = 9;
  bool bold = false;
  bool italic = false;
  bool underline = false;
  Qt::AlignmentFlag contentAlign = Qt::AlignmentFlag::AlignLeft;
  QString contentColor = "#FFFFFF";
  QString contentBackgroundColor = "transparent";
  QString windowScale = "";
  QString defaultDirectory = "";
  QString fileName = "";
  QString content = "";
  bool isSaved = false;
  QString scrollPosition = "";
  QString appTheme = "light";
  QString appLanguage = "1252";
  int adaptiveResponse = 1;
  QString readFilter =
      "General File (*.rsdoc *.docx);;HTML (*.html);;Text (*.txt);;Key-Value "
      "(*.ini);;LOG (*.log);;JavaScript Object Notation (*.json);;Extensible "
      "Markup Language (*.xml);;Javascript (*.js);;Cascading Style Sheets "
      "(*.css);;Structured Query Language (*.sql);;Markdown (*.md)";
  QString writeFilter =
      "SolidWriting Document (*.rsdoc);;HTML (*.html);;Text (*.txt);;Key-Value "
      "(*.ini);;LOG (*.log);;JavaScript Object Notation (*.json);;Extensible "
      "Markup Language (*.xml);;Javascript (*.js);;Cascading Style Sheets "
      "(*.css);;Structured Query Language (*.sql);;Markdown (*.md)";
  QString mediaFilter = "General (*.png *.jpg *.jpeg *.bmp);;Animation (*.gif)";
};

const QMap<QString, QString> languages = {
    {"1252", "English"},        {"1031", "Deutsch"},      {"1034", "Español"},
    {"1055", "Türkçe"},         {"1068", "Azərbaycanca"}, {"1091", "Uzbek"},
    {"2052", "中文"},                                 // Chinese
    {"1042", "한국어"},                               // Korean
    {"1041", "日本語"},                               // Japanese
    {"1025", "العربية"},                              // Arabic
    {"1049", "Русский"},                              // Russian
    {"1036", "Français"},       {"1032", "Ελληνικά"}, // Greek
    {"1037", "Hebrew (עברית)"},
};

const QMap<QString, QMap<QString, QString>> translations = {
    {"1252",
     {{"new", "New"},
      {"open", "Open"},
      {"save", "Save"},
      {"save_as", "Save As"},
      {"print", "Print"},
      {"exit", "Exit"},
      {"file", "File"},
      {"interface", "Interface"},
      {"ui", "UI"},
      {"format", "Format"},
      {"alignment", "Alignment"},
      {"color", "Color"},
      {"multimedia", "Multimedia"},
      {"darklight", "Dark/Light"},
      {"darklight_message", "Change theme"},
      {"edit", "Edit"},
      {"view", "View"},
      {"viewmode", "View Mode"},
      {"viewmode_message", "Change view mode"},
      {"help", "Help"},
      {"help_message", "Help"},
      {"help_shortcut", "Shortcuts"},
      {"help_description", "Description"},
      {"about", "About"},
      {"new_message", "New document"},
      {"open_message", "Open document"},
      {"save_message", "Save document"},
      {"save_as_message", "Save document as"},
      {"print_message", "Print document"},
      {"find", "Find"},
      {"find_message", "Find text"},
      {"replace", "Replace"},
      {"replace_message", "Replace text"},
      {"undo", "Undo"},
      {"undo_message", "Undo action"},
      {"redo", "Redo"},
      {"redo_message", "Redo action"},
      {"right", "Right"},
      {"right_message", "Right align text"},
      {"center", "Center"},
      {"center_message", "Center align text"},
      {"left", "Left"},
      {"left_message", "Left align text"},
      {"justify", "Justify"},
      {"justify_message", "Justify text"},
      {"font", "Font"},
      {"font_message", "Change font"},
      {"font_size", "Font Size"},
      {"font_size_message", "Change font size"},
      {"font_color", "Font Color"},
      {"font_color_message", "Change font color"},
      {"contentBackgroundColor", "Background Color"},
      {"contentBackgroundColor_message", "Change background color"},
      {"bold", "Bold"},
      {"bold_message", "Bold text"},
      {"italic", "Italic"},
      {"italic_message", "Italic text"},
      {"underline", "Underline"},
      {"underline_message", "Underline text"},
      {"inc_font_message", "Increase font size"},
      {"dec_font_message", "Decrease font size"},
      {"image", "Image"},
      {"image_message", "Insert image"},
      {"untitled", "Untitled"},
      {"statistic", "Statistic"},
      {"statistic_message_1", "Lines: {0}"},
      {"statistic_message_2", "Words: {0}"},
      {"statistic_message_3", "Characters: {0}"},
      {"statistic_message_4", "Pages: {0}"},
      {"analysis", "Analysis"},
      {"analysis_message_1", "Average Word: {0}"},
      {"analysis_message_2", "Average Line: {0}"},
      {"analysis_message_3", "Uppercase: {0}"},
      {"analysis_message_4", "Lowercase: {0}"},
      {"analysis_message_5", "Language: {0}"},
      {"exit_message", "Are you sure you want to exit?"},
      {"login_success", "Login successful, redirecting..."},
      {"error", "Error"},
      {"fill_all", "Please fill all fields."},
      {"register_success", "Registration successful, please login."},
      {"already_registered", "Already registered"},
      {"email", "Email"},
      {"password", "Password"},
      {"login", "Login"},
      {"register", "Register"},
      {"powersaver", "Power Saver"},
      {"readonly", " — Read Only"}}},
    {"1055",
     {{"new", "Yeni"},
      {"open", "Aç"},
      {"save", "Kaydet"},
      {"save_as", "Farklı Kaydet"},
      {"print", "Yazdır"},
      {"exit", "Çık"},
      {"file", "Dosya"},
      {"interface", "Arayüz"},
      {"ui", "Kullanıcı Arayüzü"},
      {"format", "Biçim"},
      {"alignment", "Hizalama"},
      {"color", "Renk"},
      {"multimedia", "Multimedya"},
      {"darklight", "Koyu/Aydınlık"},
      {"darklight_message", "Tema değiştir"},
      {"edit", "Düzenle"},
      {"view", "Görünüm"},
      {"viewmode", "Görünüm Modu"},
      {"viewmode_message", "Görünüm modunu değiştir"},
      {"help", "Yardım"},
      {"help_message", "Yardım"},
      {"help_shortcut", "Kısayollar"},
      {"help_description", "Açıklama"},
      {"about", "Hakkında"},
      {"new_message", "Yeni belge"},
      {"open_message", "Belge aç"},
      {"save_message", "Belgeyi kaydet"},
      {"save_as_message", "Belgeyi farklı kaydet"},
      {"print_message", "Belgeyi yazdır"},
      {"find", "Bul"},
      {"find_message", "Metin bul"},
      {"replace", "Değiştir"},
      {"replace_message", "Metni değiştir"},
      {"undo", "Geri al"},
      {"undo_message", "İşlemi geri al"},
      {"redo", "Yinele"},
      {"redo_message", "İşlemi yinele"},
      {"right", "Sağ"},
      {"right_message", "Sağa hizala"},
      {"center", "Ortala"},
      {"center_message", "Ortala hizala"},
      {"left", "Sol"},
      {"left_message", "Sola hizala"},
      {"justify", "Yasla"},
      {"justify_message", "Metni yasla"},
      {"font", "Yazı Tipi"},
      {"font_message", "Yazı tipi değiştir"},
      {"font_size", "Yazı Boyutu"},
      {"font_size_message", "Yazı boyutunu değiştir"},
      {"font_color", "Yazı Rengi"},
      {"font_color_message", "Yazı rengini değiştir"},
      {"contentBackgroundColor", "Arka Plan Rengi"},
      {"contentBackgroundColor_message", "Arka plan rengini değiştir"},
      {"bold", "Kalın"},
      {"bold_message", "Kalın yazı"},
      {"italic", "İtalik"},
      {"italic_message", "İtalik yazı"},
      {"underline", "Altı Çizili"},
      {"underline_message", "Altı çizili yazı"},
      {"inc_font_message", "Yazı boyutunu büyüt"},
      {"dec_font_message", "Yazı boyutunu küçült"},
      {"image", "Resim"},
      {"image_message", "Resim ekle"},
      {"untitled", "Başlıksız"},
      {"statistic", "İstatistik"},
      {"statistic_message_1", "Satırlar: {0}"},
      {"statistic_message_2", "Kelimeler: {0}"},
      {"statistic_message_3", "Karakterler: {0}"},
      {"statistic_message_4", "Sayfalar: {0}"},
      {"analysis", "Analiz"},
      {"analysis_message_1", "Ortalama Kelime: {0}"},
      {"analysis_message_2", "Ortalama Satır: {0}"},
      {"analysis_message_3", "Büyük Harf: {0}"},
      {"analysis_message_4", "Küçük Harf: {0}"},
      {"analysis_message_5", "Dil: {0}"},
      {"exit_message", "Çıkmak istediğinizden emin misiniz?"},
      {"login_success", "Giriş başarılı, yönlendiriliyorsunuz..."},
      {"error", "Hata"},
      {"fill_all", "Lütfen tüm alanları doldurun."},
      {"register_success", "Kayıt başarılı, lütfen giriş yapın."},
      {"already_registered", "Zaten kayıtlı"},
      {"email", "E-posta"},
      {"password", "Şifre"},
      {"login", "Giriş"},
      {"register", "Kayıt"},
      {"powersaver", "Güç Tasarrufu"},
      {"readonly", " — Sadece Okunabilir"}}},
    {"1068",
     {{"new", "Yeni"},
      {"open", "Aç"},
      {"save", "Yadda saxla"},
      {"save_as", "Farklı Yadda saxla"},
      {"print", "Çap et"},
      {"exit", "Çıx"},
      {"file", "Fayl"},
      {"interface", "İnterfeys"},
      {"ui", "İstifadəçi İnterfeysi"},
      {"format", "Format"},
      {"alignment", "Yerləşdirmə"},
      {"color", "Rəng"},
      {"multimedia", "Multimedia"},
      {"darklight", "Qaranlıq/Aydınlıq"},
      {"darklight_message", "Tema dəyişdir"},
      {"edit", "Düzəlt"},
      {"view", "Baxış"},
      {"viewmode", "Baxış Modu"},
      {"viewmode_message", "Baxış modunu dəyişdir"},
      {"help", "Kömək"},
      {"help_message", "Kömək"},
      {"help_shortcut", "Qısa yollər"},
      {"help_description", "Təsvir"},
      {"about", "Haqqında"},
      {"new_message", "Yeni sənəd"},
      {"open_message", "Sənəd aç"},
      {"save_message", "Sənədi yadda saxla"},
      {"save_as_message", "Sənədi fərqli yadda saxla"},
      {"print_message", "Sənədi çap et"},
      {"find", "Tap"},
      {"find_message", "Mətni tap"},
      {"replace", "Dəyişdir"},
      {"replace_message", "Mətni dəyişdir"},
      {"undo", "Geri al"},
      {"undo_message", "Əməliyyatı geri al"},
      {"redo", "Təkrarla"},
      {"redo_message", "Əməliyyatı təkrarla"},
      {"right", "Sağ"},
      {"right_message", "Sağa hizala"},
      {"center", "Mərkəz"},
      {"center_message", "Mərkəzlə hizala"},
      {"left", "Sol"},
      {"left_message", "Sola hizala"},
      {"justify", "Sıxışdır"},
      {"justify_message", "Mətni sıxışdır"},
      {"font", "Yazı tipi"},
      {"font_message", "Yazı tipini dəyişdir"},
      {"font_size", "Yazı ölçüsü"},
      {"font_size_message", "Yazı ölçüsünü dəyişdir"},
      {"font_color", "Yazı rəngi"},
      {"font_color_message", "Yazı rəngini dəyişdir"},
      {"contentBackgroundColor", "Arxa plan rəngi"},
      {"contentBackgroundColor_message", "Arxa plan rəngini dəyişdir"},
      {"bold", "Qalın"},
      {"bold_message", "Qalın mətn"},
      {"italic", "İtalik"},
      {"italic_message", "İtalik mətn"},
      {"underline", "Altı xətlidir"},
      {"underline_message", "Altı xətti mətn"},
      {"inc_font_message", "Yazı ölçüsünü artır"},
      {"dec_font_message", "Yazı ölçüsünü azald"},
      {"image", "Şəkil"},
      {"image_message", "Şəkil əlavə et"},
      {"untitled", "Başlıqsız"},
      {"statistic", "Statistika"},
      {"statistic_message_1", "Sətirlər: {0}"},
      {"statistic_message_2", "Kəlmələr: {0}"},
      {"statistic_message_3", "Simvollar: {0}"},
      {"statistic_message_4", "Səhifələr: {0}"},
      {"analysis", "Analiz"},
      {"analysis_message_1", "Ortalama Kəlmə: {0}"},
      {"analysis_message_2", "Ortalama Sətir: {0}"},
      {"analysis_message_3", "Böyük Hərf: {0}"},
      {"analysis_message_4", "Kiçik Hərf: {0}"},
      {"analysis_message_5", "Dil: {0}"},
      {"exit_message", "Çıxmaq istədiyinizə əminsiniz?"},
      {"login_success", "Giriş uğurlu oldu, yönləndiriliyorsunuz..."},
      {"error", "Xəta"},
      {"fill_all", "Bütün sahələri doldurun."},
      {"register_success", "Qeydiyyat uğurlu oldu, xahiş edirik daxil olun."},
      {"already_registered", "Zaten qeydiyyatdan keçmisiniz"},
      {"email", "E-poçt"},
      {"password", "Şifrə"},
      {"login", "Daxil ol"},
      {"register", "Qeydiyyatdan keç"},
      {"powersaver", "Enerji Qənaəti"},
      {"readonly", " — Yalnız Oxumaq"}}},
    {"1031",
     {{"new", "Neu"},
      {"open", "Öffnen"},
      {"save", "Speichern"},
      {"save_as", "Speichern unter"},
      {"print", "Drucken"},
      {"exit", "Beenden"},
      {"file", "Datei"},
      {"interface", "Schnittstelle"},
      {"ui", "Benutzeroberfläche"},
      {"format", "Format"},
      {"alignment", "Ausrichtung"},
      {"color", "Farbe"},
      {"multimedia", "Multimedia"},
      {"darklight", "Dunkel/Hell"},
      {"darklight_message", "Thema ändern"},
      {"edit", "Bearbeiten"},
      {"view", "Ansicht"},
      {"viewmode", "Ansichtsmodus"},
      {"viewmode_message", "Ansichtsmodus ändern"},
      {"help", "Hilfe"},
      {"help_message", "Hilfe"},
      {"help_shortcut", "Tastenkürzel"},
      {"help_description", "Beschreibung"},
      {"about", "Über"},
      {"new_message", "Neues Dokument"},
      {"open_message", "Dokument öffnen"},
      {"save_message", "Dokument speichern"},
      {"save_as_message", "Dokument speichern unter"},
      {"print_message", "Dokument drucken"},
      {"find", "Suchen"},
      {"find_message", "Text suchen"},
      {"replace", "Ersetzen"},
      {"replace_message", "Text ersetzen"},
      {"undo", "Rückgängig"},
      {"undo_message", "Aktion rückgängig machen"},
      {"redo", "Wiederholen"},
      {"redo_message", "Aktion wiederholen"},
      {"right", "Rechts"},
      {"right_message", "Text rechts ausrichten"},
      {"center", "Zentrieren"},
      {"center_message", "Text zentrieren"},
      {"left", "Links"},
      {"left_message", "Text links ausrichten"},
      {"justify", "Blocksatz"},
      {"justify_message", "Text im Blocksatz"},
      {"font", "Schriftart"},
      {"font_message", "Schriftart ändern"},
      {"font_size", "Schriftgröße"},
      {"font_size_message", "Schriftgröße ändern"},
      {"font_color", "Schriftfarbe"},
      {"font_color_message", "Schriftfarbe ändern"},
      {"contentBackgroundColor", "Hintergrundfarbe"},
      {"contentBackgroundColor_message", "Hintergrundfarbe ändern"},
      {"bold", "Fett"},
      {"bold_message", "Fettgedruckten Text"},
      {"italic", "Kursiv"},
      {"italic_message", "Kursiven Text"},
      {"underline", "Unterstrichen"},
      {"underline_message", "Unterstrichenen Text"},
      {"inc_font_message", "Schriftgröße erhöhen"},
      {"dec_font_message", "Schriftgröße verringern"},
      {"image", "Bild"},
      {"image_message", "Bild einfügen"},
      {"untitled", "Unbenannt"},
      {"statistic", "Statistik"},
      {"statistic_message_1", "Zeilen: {0}"},
      {"statistic_message_2", "Wörter: {0}"},
      {"statistic_message_3", "Zeichen: {0}"},
      {"statistic_message_4", "Seiten: {0}"},
      {"analysis", "Analyse"},
      {"analysis_message_1", "Durchschnittliches Wort: {0}"},
      {"analysis_message_2", "Durchschnittliche Zeile: {0}"},
      {"analysis_message_3", "Großbuchstaben: {0}"},
      {"analysis_message_4", "Kleinbuchstaben: {0}"},
      {"analysis_message_5", "Sprache: {0}"},
      {"exit_message", "Sind Sie sicher, dass Sie beenden möchten?"},
      {"login_success", "Login erfolgreich, Weiterleitung..."},
      {"error", "Fehler"},
      {"fill_all", "Bitte füllen Sie alle Felder aus."},
      {"register_success", "Registrierung erfolgreich, bitte anmelden."},
      {"already_registered", "Bereits registriert"},
      {"email", "E-Mail"},
      {"password", "Passwort"},
      {"login", "Anmelden"},
      {"register", "Registrieren"},
      {"powersaver", "Energiesparmodus"},
      {"readonly", " — Nur Lesen"}}},
    {"1034",
     {{"new", "Nuevo"},
      {"open", "Abrir"},
      {"save", "Guardar"},
      {"save_as", "Guardar como"},
      {"print", "Imprimir"},
      {"exit", "Salir"},
      {"file", "Archivo"},
      {"interface", "Interfaz"},
      {"ui", "Interfaz de usuario"},
      {"format", "Formato"},
      {"alignment", "Alineación"},
      {"color", "Color"},
      {"multimedia", "Multimedia"},
      {"darklight", "Oscuro/Claro"},
      {"darklight_message", "Cambiar tema"},
      {"edit", "Editar"},
      {"view", "Ver"},
      {"viewmode", "Modo de vista"},
      {"viewmode_message", "Cambiar modo de vista"},
      {"help", "Ayuda"},
      {"help_message", "Ayuda"},
      {"help_shortcut", "Accesos rápidos"},
      {"help_description", "Descripción"},
      {"about", "Acerca de"},
      {"new_message", "Nuevo documento"},
      {"open_message", "Abrir documento"},
      {"save_message", "Guardar documento"},
      {"save_as_message", "Guardar documento como"},
      {"print_message", "Imprimir documento"},
      {"find", "Buscar"},
      {"find_message", "Buscar texto"},
      {"replace", "Reemplazar"},
      {"replace_message", "Reemplazar texto"},
      {"undo", "Deshacer"},
      {"undo_message", "Deshacer acción"},
      {"redo", "Rehacer"},
      {"redo_message", "Rehacer acción"},
      {"right", "Derecha"},
      {"right_message", "Alinear texto a la derecha"},
      {"center", "Centro"},
      {"center_message", "Alinear texto al centro"},
      {"left", "Izquierda"},
      {"left_message", "Alinear texto a la izquierda"},
      {"justify", "Justificar"},
      {"justify_message", "Justificar texto"},
      {"font", "Fuente"},
      {"font_message", "Cambiar fuente"},
      {"font_size", "Tamaño de fuente"},
      {"font_size_message", "Cambiar tamaño de fuente"},
      {"font_color", "Color de fuente"},
      {"font_color_message", "Cambiar color de fuente"},
      {"contentBackgroundColor", "Color de fondo"},
      {"contentBackgroundColor_message", "Cambiar color de fondo"},
      {"bold", "Negrita"},
      {"bold_message", "Texto en negrita"},
      {"italic", "Cursiva"},
      {"italic_message", "Texto en cursiva"},
      {"underline", "Subrayado"},
      {"underline_message", "Texto subrayado"},
      {"inc_font_message", "Aumentar tamaño de fuente"},
      {"dec_font_message", "Disminuir tamaño de fuente"},
      {"image", "Imagen"},
      {"image_message", "Insertar imagen"},
      {"untitled", "Sin título"},
      {"statistic", "Estadísticas"},
      {"statistic_message_1", "Líneas: {0}"},
      {"statistic_message_2", "Palabras: {0}"},
      {"statistic_message_3", "Caracteres: {0}"},
      {"statistic_message_4", "Páginas: {0}"},
      {"analysis", "Análisis"},
      {"analysis_message_1", "Promedio de palabras: {0}"},
      {"analysis_message_2", "Promedio de líneas: {0}"},
      {"analysis_message_3", "Mayúsculas: {0}"},
      {"analysis_message_4", "Minúsculas: {0}"},
      {"analysis_message_5", "Idioma: {0}"},
      {"exit_message", "¿Estás seguro de que deseas salir?"},
      {"login_success", "Inicio de sesión exitoso, redirigiendo..."},
      {"error", "Error"},
      {"fill_all", "Por favor, complete todos los campos."},
      {"register_success", "Registro exitoso, por favor inicie sesión."},
      {"already_registered", "Ya registrado"},
      {"email", "Correo electrónico"},
      {"password", "Contraseña"},
      {"login", "Iniciar sesión"},
      {"register", "Registrarse"},
      {"powersaver", "Ahorro de energía"},
      {"readonly", " — Solo lectura"}}},
    {"1091",
     {{"new", "Yangi"},
      {"open", "Ochish"},
      {"save", "Saqlash"},
      {"save_as", "Saqlash sifatida"},
      {"print", "Chop etish"},
      {"exit", "Chiqish"},
      {"file", "Fayl"},
      {"interface", "Interfeys"},
      {"ui", "Foydalanuvchi interfeysi"},
      {"format", "Format"},
      {"alignment", "Joylashtirish"},
      {"color", "Rang"},
      {"multimedia", "Multimedia"},
      {"darklight", "Qorong'u/Yorug'lik"},
      {"darklight_message", "Mavzuni o'zgartirish"},
      {"edit", "Tahrirlash"},
      {"view", "Ko'rish"},
      {"viewmode", "Ko'rish rejimi"},
      {"viewmode_message", "Ko'rish rejimini o'zgartirish"},
      {"help", "Yordam"},
      {"help_message", "Yordam"},
      {"help_shortcut", "Klaviatura qisqa tugmalari"},
      {"help_description", "Tavsif"},
      {"about", "Haqida"},
      {"new_message", "Yangi hujjat"},
      {"open_message", "Hujjatni ochish"},
      {"save_message", "Hujjatni saqlash"},
      {"save_as_message", "Hujjatni saqlash sifatida"},
      {"print_message", "Hujjatni chop etish"},
      {"find", "Topish"},
      {"find_message", "Matnni topish"},
      {"replace", "Almashtirish"},
      {"replace_message", "Matnni almashtirish"},
      {"undo", "Orqaga qaytarish"},
      {"undo_message", "Amaliyotni orqaga qaytarish"},
      {"redo", "Qayta bajarish"},
      {"redo_message", "Amaliyotni qayta bajarish"},
      {"right", "O'ng"},
      {"right_message", "Matnni o'ngga tekislash"},
      {"center", "Markaz"},
      {"center_message", "Matnni markazlashtirish"},
      {"left", "Chap"},
      {"left_message", "Matnni chapga tekislash"},
      {"justify", "To'liq tekislash"},
      {"justify_message", "Matnni to'liq tekislash"},
      {"font", "Shrift"},
      {"font_message", "Shriftni o'zgartirish"},
      {"font_size", "Shrift o'lchami"},
      {"font_size_message", "Shrift o'lchamini o'zgartirish"},
      {"font_color", "Shrift rangi"},
      {"font_color_message", "Shrift rangini o'zgartirish"},
      {"contentBackgroundColor", "Orqa fon rangi"},
      {"contentBackgroundColor_message", "Orqa fon rangini o'zgartirish"},
      {"bold", "Qalin"},
      {"bold_message", "Qalin matn"},
      {"italic", "Kursiv"},
      {"italic_message", "Kursiv matn"},
      {"underline", "Chizilgan"},
      {"underline_message", "Chizilgan matn"},
      {"inc_font_message", "Shrift o'lchamini oshirish"},
      {"dec_font_message", "Shrift o'lchamini kamaytirish"},
      {"image", "Rasm"},
      {"image_message", "Rasm qo'shish"},
      {"untitled", "Nomlanmagan"},
      {"statistic", "Statistika"},
      {"statistic_message_1", "Qatorlar: {0}"},
      {"statistic_message_2", "So'zlar: {0}"},
      {"statistic_message_3", "Belgilar: {0}"},
      {"statistic_message_4", "Sahifalar: {0}"},
      {"analysis", "Tahlil"},
      {"analysis_message_1", "O'rtacha so'z: {0}"},
      {"analysis_message_2", "O'rtacha qator: {0}"},
      {"analysis_message_3", "Katta harflar: {0}"},
      {"analysis_message_4", "Kichik harflar: {0}"},
      {"analysis_message_5", "Til: {0}"},
      {"exit_message", "Chiqishni xohlaysizmi?"},
      {"login_success", "Kirish muvaffaqiyatli, yo'naltirilmoqda..."},
      {"error", "Xato"},
      {"fill_all", "Iltimos, barcha maydonlarni to'ldiring."},
      {"register_success",
       "Ro'yxatdan o'tish muvaffaqiyatli, iltimos, tizimga kiring."},
      {"already_registered", "Allaqachon ro'yxatdan o'tgan"},
      {"email", "Elektron pochta"},
      {"password", "Parol"},
      {"login", "Kirish"},
      {"register", "Ro'yxatdan o'tish"},
      {"powersaver", "Quvvat tejash"},
      {"readonly", " — Faqat o'qish"}}},
    {"2052",
     {{"new", "新建"},
      {"open", "打开"},
      {"save", "保存"},
      {"save_as", "另存为"},
      {"print", "打印"},
      {"exit", "退出"},
      {"file", "文件"},
      {"interface", "界面"},
      {"ui", "用户界面"},
      {"format", "格式"},
      {"alignment", "对齐"},
      {"color", "颜色"},
      {"multimedia", "多媒体"},
      {"darklight", "深色/浅色"},
      {"darklight_message", "更改主题"},
      {"edit", "编辑"},
      {"view", "查看"},
      {"viewmode", "视图模式"},
      {"viewmode_message", "更改视图模式"},
      {"help", "帮助"},
      {"help_message", "帮助"},
      {"help_shortcut", "快捷键"},
      {"help_description", "描述"},
      {"about", "关于"},
      {"new_message", "新建文档"},
      {"open_message", "打开文档"},
      {"save_message", "保存文档"},
      {"save_as_message", "另存为文档"},
      {"print_message", "打印文档"},
      {"find", "查找"},
      {"find_message", "查找文本"},
      {"replace", "替换"},
      {"replace_message", "替换文本"},
      {"undo", "撤销"},
      {"undo_message", "撤销操作"},
      {"redo", "重做"},
      {"redo_message", "重做操作"},
      {"right", "右对齐"},
      {"right_message", "将文本右对齐"},
      {"center", "居中"},
      {"center_message", "将文本居中"},
      {"left", "左对齐"},
      {"left_message", "将文本左对齐"},
      {"justify", "两端对齐"},
      {"justify_message", "将文本两端对齐"},
      {"font", "字体"},
      {"font_message", "更改字体"},
      {"font_size", "字体大小"},
      {"font_size_message", "更改字体大小"},
      {"font_color", "字体颜色"},
      {"font_color_message", "更改字体颜色"},
      {"contentBackgroundColor", "背景颜色"},
      {"contentBackgroundColor_message", "更改背景颜色"},
      {"bold", "加粗"},
      {"bold_message", "加粗文本"},
      {"italic", "斜体"},
      {"italic_message", "斜体文本"},
      {"underline", "下划线"},
      {"underline_message", "下划线文本"},
      {"inc_font_message", "增加字体大小"},
      {"dec_font_message", "减少字体大小"},
      {"image", "图片"},
      {"image_message", "插入图片"},
      {"untitled", "未命名"},
      {"statistic", "统计"},
      {"statistic_message_1", "行数：{0}"},
      {"statistic_message_2", "字数：{0}"},
      {"statistic_message_3", "字符数：{0}"},
      {"statistic_message_4", "页数：{0}"},
      {"analysis", "分析"},
      {"analysis_message_1", "平均字数：{0}"},
      {"analysis_message_2", "平均行数：{0}"},
      {"analysis_message_3", "大写字母：{0}"},
      {"analysis_message_4", "小写字母：{0}"},
      {"analysis_message_5", "语言：{0}"},
      {"exit_message", "你确定要退出吗？"},
      {"login_success", "登录成功，正在重定向..."},
      {"error", "错误"},
      {"fill_all", "请填写所有字段。"},
      {"register_success", "注册成功，请登录。"},
      {"already_registered", "已注册"},
      {"email", "电子邮件"},
      {"password", "密码"},
      {"login", "登录"},
      {"register", "注册"},
      {"powersaver", "省电模式"},
      {"readonly", " — 只读"}}},
    {"1042",
     {{"new", "새로 만들기"},
      {"open", "열기"},
      {"save", "저장"},
      {"save_as", "다른 이름으로 저장"},
      {"print", "인쇄"},
      {"exit", "종료"},
      {"file", "파일"},
      {"interface", "인터페이스"},
      {"ui", "사용자 인터페이스"},
      {"format", "형식"},
      {"alignment", "정렬"},
      {"color", "색상"},
      {"multimedia", "멀티미디어"},
      {"darklight", "어두운/밝은"},
      {"darklight_message", "테마 변경"},
      {"edit", "편집"},
      {"view", "보기"},
      {"viewmode", "보기 모드"},
      {"viewmode_message", "보기 모드 변경"},
      {"help", "도움말"},
      {"help_message", "도움말"},
      {"help_shortcut", "단축키"},
      {"help_description", "설명"},
      {"about", "정보"},
      {"new_message", "새 문서"},
      {"open_message", "문서 열기"},
      {"save_message", "문서 저장"},
      {"save_as_message", "문서 다른 이름으로 저장"},
      {"print_message", "문서 인쇄"},
      {"find", "찾기"},
      {"find_message", "텍스트 찾기"},
      {"replace", "바꾸기"},
      {"replace_message", "텍스트 바꾸기"},
      {"undo", "실행 취소"},
      {"undo_message", "작업 실행 취소"},
      {"redo", "다시 실행"},
      {"redo_message", "작업 다시 실행"},
      {"right", "오른쪽 정렬"},
      {"right_message", "텍스트 오른쪽 정렬"},
      {"center", "가운데 정렬"},
      {"center_message", "텍스트 가운데 정렬"},
      {"left", "왼쪽 정렬"},
      {"left_message", "텍스트 왼쪽 정렬"},
      {"justify", "양쪽 정렬"},
      {"justify_message", "텍스트 양쪽 정렬"},
      {"font", "글꼴"},
      {"font_message", "글꼴 변경"},
      {"font_size", "글꼴 크기"},
      {"font_size_message", "글꼴 크기 변경"},
      {"font_color", "글꼴 색상"},
      {"font_color_message", "글꼴 색상 변경"},
      {"contentBackgroundColor", "배경 색상"},
      {"contentBackgroundColor_message", "배경 색상 변경"},
      {"bold", "굵게"},
      {"bold_message", "굵은 텍스트"},
      {"italic", "기울임꼴"},
      {"italic_message", "기울임꼴 텍스트"},
      {"underline", "밑줄"},
      {"underline_message", "밑줄 텍스트"},
      {"inc_font_message", "글꼴 크기 늘리기"},
      {"dec_font_message", "글꼴 크기 줄이기"},
      {"image", "이미지"},
      {"image_message", "이미지 삽입"},
      {"untitled", "제목 없음"},
      {"statistic", "통계"},
      {"statistic_message_1", "줄 수: {0}"},
      {"statistic_message_2", "단어 수: {0}"},
      {"statistic_message_3", "문자 수: {0}"},
      {"statistic_message_4", "페이지 수: {0}"},
      {"analysis", "분석"},
      {"analysis_message_1", "평균 단어: {0}"},
      {"analysis_message_2", "평균 줄: {0}"},
      {"analysis_message_3", "대문자: {0}"},
      {"analysis_message_4", "소문자: {0}"},
      {"analysis_message_5", "언어: {0}"},
      {"exit_message", "정말로 종료하시겠습니까?"},
      {"login_success", "로그인 성공, 리디렉션 중..."},
      {"error", "오류"},
      {"fill_all", "모든 필드를 채워주세요."},
      {"register_success", "회원가입 성공, 로그인 해주세요."},
      {"already_registered", "이미 등록되었습니다"},
      {"email", "이메일"},
      {"password", "비밀번호"},
      {"login", "로그인"},
      {"register", "회원가입"},
      {"powersaver", "전원 절약 모드"},
      {"readonly", " — 읽기 전용"}}},
    {"1041",
     {{"new", "新規作成"},
      {"open", "開く"},
      {"save", "保存"},
      {"save_as", "名前を付けて保存"},
      {"print", "印刷"},
      {"exit", "終了"},
      {"file", "ファイル"},
      {"interface", "インターフェース"},
      {"ui", "ユーザーインターフェース"},
      {"format", "フォーマット"},
      {"alignment", "配置"},
      {"color", "色"},
      {"multimedia", "マルチメディア"},
      {"darklight", "ダーク/ライト"},
      {"darklight_message", "テーマを変更"},
      {"edit", "編集"},
      {"view", "表示"},
      {"viewmode", "表示モード"},
      {"viewmode_message", "表示モードを変更"},
      {"help", "ヘルプ"},
      {"help_message", "ヘルプ"},
      {"help_shortcut", "ショートカット"},
      {"help_description", "説明"},
      {"about", "について"},
      {"new_message", "新しい文書"},
      {"open_message", "文書を開く"},
      {"save_message", "文書を保存"},
      {"save_as_message", "文書を名前を付けて保存"},
      {"print_message", "文書を印刷"},
      {"find", "検索"},
      {"find_message", "テキストを検索"},
      {"replace", "置換"},
      {"replace_message", "テキストを置換"},
      {"undo", "元に戻す"},
      {"undo_message", "操作を元に戻す"},
      {"redo", "やり直し"},
      {"redo_message", "操作をやり直す"},
      {"right", "右揃え"},
      {"right_message", "テキストを右揃え"},
      {"center", "中央揃え"},
      {"center_message", "テキストを中央揃え"},
      {"left", "左揃え"},
      {"left_message", "テキストを左揃え"},
      {"justify", "両端揃え"},
      {"justify_message", "テキストを両端揃え"},
      {"font", "フォント"},
      {"font_message", "フォントを変更"},
      {"font_size", "フォントサイズ"},
      {"font_size_message", "フォントサイズを変更"},
      {"font_color", "フォントカラー"},
      {"font_color_message", "フォントカラーを変更"},
      {"contentBackgroundColor", "背景色"},
      {"contentBackgroundColor_message", "背景色を変更"},
      {"bold", "太字"},
      {"bold_message", "太字のテキスト"},
      {"italic", "斜体"},
      {"italic_message", "斜体のテキスト"},
      {"underline", "下線"},
      {"underline_message", "下線付きのテキスト"},
      {"inc_font_message", "フォントサイズを増加"},
      {"dec_font_message", "フォントサイズを減少"},
      {"image", "画像"},
      {"image_message", "画像を挿入"},
      {"untitled", "無題"},
      {"statistic", "統計"},
      {"statistic_message_1", "行数: {0}"},
      {"statistic_message_2", "単語数: {0}"},
      {"statistic_message_3", "文字数: {0}"},
      {"statistic_message_4", "ページ数: {0}"},
      {"analysis", "分析"},
      {"analysis_message_1", "平均単語数: {0}"},
      {"analysis_message_2", "平均行数: {0}"},
      {"analysis_message_3", "大文字: {0}"},
      {"analysis_message_4", "小文字: {0}"},
      {"analysis_message_5", "言語: {0}"},
      {"exit_message", "本当に終了しますか？"},
      {"login_success", "ログインに成功しました。リダイレクト中..."},
      {"error", "エラー"},
      {"fill_all", "すべてのフィールドを入力してください。"},
      {"register_success", "登録が成功しました。ログインしてください。"},
      {"already_registered", "既に登録されています"},
      {"email", "メールアドレス"},
      {"password", "パスワード"},
      {"login", "ログイン"},
      {"register", "登録"},
      {"powersaver", "省電力モード"},
      {"readonly", " — 読み取り専用"}}},
    {"1025",
     {{"new", "جديد"},
      {"open", "فتح"},
      {"save", "حفظ"},
      {"save_as", "حفظ باسم"},
      {"print", "طباعة"},
      {"exit", "خروج"},
      {"file", "ملف"},
      {"interface", "واجهة"},
      {"ui", "واجهة المستخدم"},
      {"format", "تنسيق"},
      {"alignment", "محاذاة"},
      {"color", "لون"},
      {"multimedia", "وسائط متعددة"},
      {"darklight", "داكن/فاتح"},
      {"darklight_message", "تغيير السمة"},
      {"edit", "تعديل"},
      {"view", "عرض"},
      {"viewmode", "وضع العرض"},
      {"viewmode_message", "تغيير وضع العرض"},
      {"help", "مساعدة"},
      {"help_message", "مساعدة"},
      {"help_shortcut", "اختصارات"},
      {"help_description", "وصف"},
      {"about", "معلومات"},
      {"new_message", "مستند جديد"},
      {"open_message", "فتح مستند"},
      {"save_message", "حفظ مستند"},
      {"save_as_message", "حفظ المستند باسم"},
      {"print_message", "طباعة المستند"},
      {"find", "بحث"},
      {"find_message", "بحث عن نص"},
      {"replace", "استبدال"},
      {"replace_message", "استبدال النص"},
      {"undo", "تراجع"},
      {"undo_message", "تراجع عن الإجراء"},
      {"redo", "إعادة"},
      {"redo_message", "إعادة الإجراء"},
      {"right", "محاذاة لليمين"},
      {"right_message", "محاذاة النص لليمين"},
      {"center", "محاذاة للوسط"},
      {"center_message", "محاذاة النص للوسط"},
      {"left", "محاذاة لليسار"},
      {"left_message", "محاذاة النص لليسار"},
      {"justify", "محاذاة كاملة"},
      {"justify_message", "محاذاة النص"},
      {"font", "خط"},
      {"font_message", "تغيير الخط"},
      {"font_size", "حجم الخط"},
      {"font_size_message", "تغيير حجم الخط"},
      {"font_color", "لون الخط"},
      {"font_color_message", "تغيير لون الخط"},
      {"contentBackgroundColor", "لون الخلفية"},
      {"contentBackgroundColor_message", "تغيير لون الخلفية"},
      {"bold", "عريض"},
      {"bold_message", "نص عريض"},
      {"italic", "مائل"},
      {"italic_message", "نص مائل"},
      {"underline", "تسطير"},
      {"underline_message", "نص مسطر"},
      {"inc_font_message", "زيادة حجم الخط"},
      {"dec_font_message", "تقليص حجم الخط"},
      {"image", "صورة"},
      {"image_message", "إدراج صورة"},
      {"untitled", "بدون عنوان"},
      {"statistic", "إحصائيات"},
      {"statistic_message_1", "عدد الأسطر: {0}"},
      {"statistic_message_2", "عدد الكلمات: {0}"},
      {"statistic_message_3", "عدد الأحرف: {0}"},
      {"statistic_message_4", "عدد الصفحات: {0}"},
      {"analysis", "تحليل"},
      {"analysis_message_1", "متوسط الكلمات: {0}"},
      {"analysis_message_2", "متوسط الأسطر: {0}"},
      {"analysis_message_3", "أحرف كبيرة: {0}"},
      {"analysis_message_4", "أحرف صغيرة: {0}"},
      {"analysis_message_5", "اللغة: {0}"},
      {"exit_message", "هل أنت متأكد من أنك تريد الخروج؟"},
      {"login_success", "تم تسجيل الدخول بنجاح، جارٍ التوجيه..."},
      {"error", "خطأ"},
      {"fill_all", "يرجى ملء جميع الحقول."},
      {"register_success", "تم التسجيل بنجاح، يرجى تسجيل الدخول."},
      {"already_registered", "تم التسجيل بالفعل"},
      {"email", "البريد الإلكتروني"},
      {"password", "كلمة المرور"},
      {"login", "تسجيل الدخول"},
      {"register", "تسجيل"},
      {"powersaver", "وضع توفير الطاقة"},
      {"readonly", " — للقراءة فقط"}}},
    {"1049",
     {{"new", "Новый"},
      {"open", "Открыть"},
      {"save", "Сохранить"},
      {"save_as", "Сохранить как"},
      {"print", "Печать"},
      {"exit", "Выход"},
      {"file", "Файл"},
      {"interface", "Интерфейс"},
      {"ui", "Пользовательский интерфейс"},
      {"format", "Формат"},
      {"alignment", "Выравнивание"},
      {"color", "Цвет"},
      {"multimedia", "Мультимедиа"},
      {"darklight", "Темная/Светлая"},
      {"darklight_message", "Изменить тему"},
      {"edit", "Правка"},
      {"view", "Вид"},
      {"viewmode", "Режим отображения"},
      {"viewmode_message", "Изменить режим отображения"},
      {"help", "Помощь"},
      {"help_message", "Помощь"},
      {"help_shortcut", "Горячие клавиши"},
      {"help_description", "Описание"},
      {"about", "О программе"},
      {"new_message", "Новый документ"},
      {"open_message", "Открыть документ"},
      {"save_message", "Сохранить документ"},
      {"save_as_message", "Сохранить документ как"},
      {"print_message", "Распечатать документ"},
      {"find", "Найти"},
      {"find_message", "Найти текст"},
      {"replace", "Заменить"},
      {"replace_message", "Заменить текст"},
      {"undo", "Отменить"},
      {"undo_message", "Отменить действие"},
      {"redo", "Повторить"},
      {"redo_message", "Повторить действие"},
      {"right", "По правому краю"},
      {"right_message", "Выравнивание текста по правому краю"},
      {"center", "По центру"},
      {"center_message", "Выравнивание текста по центру"},
      {"left", "По левому краю"},
      {"left_message", "Выравнивание текста по левому краю"},
      {"justify", "По ширине"},
      {"justify_message", "Выравнивание текста по ширине"},
      {"font", "Шрифт"},
      {"font_message", "Изменить шрифт"},
      {"font_size", "Размер шрифта"},
      {"font_size_message", "Изменить размер шрифта"},
      {"font_color", "Цвет шрифта"},
      {"font_color_message", "Изменить цвет шрифта"},
      {"contentBackgroundColor", "Цвет фона"},
      {"contentBackgroundColor_message", "Изменить цвет фона"},
      {"bold", "Жирный"},
      {"bold_message", "Жирный текст"},
      {"italic", "Курсив"},
      {"italic_message", "Курсивный текст"},
      {"underline", "Подчеркнутый"},
      {"underline_message", "Подчеркнутый текст"},
      {"inc_font_message", "Увеличить размер шрифта"},
      {"dec_font_message", "Уменьшить размер шрифта"},
      {"image", "Изображение"},
      {"image_message", "Вставить изображение"},
      {"untitled", "Без названия"},
      {"statistic", "Статистика"},
      {"statistic_message_1", "Строки: {0}"},
      {"statistic_message_2", "Слова: {0}"},
      {"statistic_message_3", "Символы: {0}"},
      {"statistic_message_4", "Страницы: {0}"},
      {"analysis", "Анализ"},
      {"analysis_message_1", "Среднее количество слов: {0}"},
      {"analysis_message_2", "Среднее количество строк: {0}"},
      {"analysis_message_3", "Прописные буквы: {0}"},
      {"analysis_message_4", "Строчные буквы: {0}"},
      {"analysis_message_5", "Язык: {0}"},
      {"exit_message", "Вы уверены, что хотите выйти?"},
      {"login_success", "Вход выполнен успешно, перенаправление..."},
      {"error", "Ошибка"},
      {"fill_all", "Пожалуйста, заполните все поля."},
      {"register_success", "Регистрация прошла успешно, пожалуйста, войдите."},
      {"already_registered", "Уже зарегистрированы"},
      {"email", "Электронная почта"},
      {"password", "Пароль"},
      {"login", "Войти"},
      {"register", "Зарегистрироваться"},
      {"powersaver", "Режим энергосбережения"},
      {"readonly", " — Только для чтения"}}},
    {"1036",
     {{"new", "Nouveau"},
      {"open", "Ouvrir"},
      {"save", "Enregistrer"},
      {"save_as", "Enregistrer sous"},
      {"print", "Imprimer"},
      {"exit", "Quitter"},
      {"file", "Fichier"},
      {"interface", "Interface"},
      {"ui", "Interface utilisateur"},
      {"format", "Format"},
      {"alignment", "Alignement"},
      {"color", "Couleur"},
      {"multimedia", "Multimédia"},
      {"darklight", "Sombre/Clair"},
      {"darklight_message", "Changer de thème"},
      {"edit", "Édition"},
      {"view", "Affichage"},
      {"viewmode", "Mode d'affichage"},
      {"viewmode_message", "Changer le mode d'affichage"},
      {"help", "Aide"},
      {"help_message", "Aide"},
      {"help_shortcut", "Raccourcis"},
      {"help_description", "Description"},
      {"about", "À propos"},
      {"new_message", "Nouveau document"},
      {"open_message", "Ouvrir un document"},
      {"save_message", "Enregistrer le document"},
      {"save_as_message", "Enregistrer le document sous"},
      {"print_message", "Imprimer le document"},
      {"find", "Rechercher"},
      {"find_message", "Rechercher du texte"},
      {"replace", "Remplacer"},
      {"replace_message", "Remplacer le texte"},
      {"undo", "Annuler"},
      {"undo_message", "Annuler l'action"},
      {"redo", "Rétablir"},
      {"redo_message", "Rétablir l'action"},
      {"right", "Aligner à droite"},
      {"right_message", "Aligner le texte à droite"},
      {"center", "Centrer"},
      {"center_message", "Aligner le texte au centre"},
      {"left", "Aligner à gauche"},
      {"left_message", "Aligner le texte à gauche"},
      {"justify", "Justifier"},
      {"justify_message", "Justifier le texte"},
      {"font", "Police"},
      {"font_message", "Changer de police"},
      {"font_size", "Taille de police"},
      {"font_size_message", "Changer la taille de police"},
      {"font_color", "Couleur de police"},
      {"font_color_message", "Changer la couleur de la police"},
      {"contentBackgroundColor", "Couleur de fond"},
      {"contentBackgroundColor_message", "Changer la couleur de fond"},
      {"bold", "Gras"},
      {"bold_message", "Texte en gras"},
      {"italic", "Italique"},
      {"italic_message", "Texte en italique"},
      {"underline", "Souligné"},
      {"underline_message", "Texte souligné"},
      {"inc_font_message", "Augmenter la taille de police"},
      {"dec_font_message", "Diminuer la taille de police"},
      {"image", "Image"},
      {"image_message", "Insérer une image"},
      {"untitled", "Sans titre"},
      {"statistic", "Statistiques"},
      {"statistic_message_1", "Lignes : {0}"},
      {"statistic_message_2", "Mots : {0}"},
      {"statistic_message_3", "Caractères : {0}"},
      {"statistic_message_4", "Pages : {0}"},
      {"analysis", "Analyse"},
      {"analysis_message_1", "Mots moyens : {0}"},
      {"analysis_message_2", "Lignes moyennes : {0}"},
      {"analysis_message_3", "Majuscules : {0}"},
      {"analysis_message_4", "Minuscules : {0}"},
      {"analysis_message_5", "Langue : {0}"},
      {"exit_message", "Êtes-vous sûr de vouloir quitter ?"},
      {"login_success", "Connexion réussie, redirection..."},
      {"error", "Erreur"},
      {"fill_all", "Veuillez remplir tous les champs."},
      {"register_success", "Inscription réussie, veuillez vous connecter."},
      {"already_registered", "Déjà inscrit"},
      {"email", "Email"},
      {"password", "Mot de passe"},
      {"login", "Connexion"},
      {"register", "S'inscrire"},
      {"powersaver", "Mode économie d'énergie"},
      {"readonly", " — Lecture seule"}}},
    {"1032",
     {{"new", "Νέο"},
      {"open", "Άνοιγμα"},
      {"save", "Αποθήκευση"},
      {"save_as", "Αποθήκευση ως"},
      {"print", "Εκτύπωση"},
      {"exit", "Έξοδος"},
      {"file", "Αρχείο"},
      {"interface", "Διεπαφή"},
      {"ui", "Διεπαφή χρήστη"},
      {"format", "Μορφή"},
      {"alignment", "Στοίχιση"},
      {"color", "Χρώμα"},
      {"multimedia", "Πολυμέσα"},
      {"darklight", "Σκοτεινό/Ανοιχτό"},
      {"darklight_message", "Αλλαγή θέματος"},
      {"edit", "Επεξεργασία"},
      {"view", "Προβολή"},
      {"viewmode", "Κατάσταση προβολής"},
      {"viewmode_message", "Αλλαγή κατάστασης προβολής"},
      {"help", "Βοήθεια"},
      {"help_message", "Βοήθεια"},
      {"help_shortcut", "Συντομεύσεις"},
      {"help_description", "Περιγραφή"},
      {"about", "Σχετικά"},
      {"new_message", "Νέο έγγραφο"},
      {"open_message", "Άνοιγμα εγγράφου"},
      {"save_message", "Αποθήκευση εγγράφου"},
      {"save_as_message", "Αποθήκευση εγγράφου ως"},
      {"print_message", "Εκτύπωση εγγράφου"},
      {"find", "Βρείτε"},
      {"find_message", "Βρείτε κείμενο"},
      {"replace", "Αντικατάσταση"},
      {"replace_message", "Αντικαταστήστε κείμενο"},
      {"undo", "Αναίρεση"},
      {"undo_message", "Αναίρεση ενέργειας"},
      {"redo", "Επαναφορά"},
      {"redo_message", "Επαναφορά ενέργειας"},
      {"right", "Δεξιά"},
      {"right_message", "Στοίχιση κειμένου στα δεξιά"},
      {"center", "Κέντρο"},
      {"center_message", "Στοίχιση κειμένου στο κέντρο"},
      {"left", "Αριστερά"},
      {"left_message", "Στοίχιση κειμένου αριστερά"},
      {"justify", "Δικαιολόγηση"},
      {"justify_message", "Δικαιολόγηση κειμένου"},
      {"font", "Γραμματοσειρά"},
      {"font_message", "Αλλαγή γραμματοσειράς"},
      {"font_size", "Μέγεθος γραμματοσειράς"},
      {"font_size_message", "Αλλαγή μεγέθους γραμματοσειράς"},
      {"font_color", "Χρώμα γραμματοσειράς"},
      {"font_color_message", "Αλλαγή χρώματος γραμματοσειράς"},
      {"contentBackgroundColor", "Χρώμα φόντου"},
      {"contentBackgroundColor_message", "Αλλαγή χρώματος φόντου"},
      {"bold", "Έντονα"},
      {"bold_message", "Έντονο κείμενο"},
      {"italic", "Πλάγια"},
      {"italic_message", "Πλάγιο κείμενο"},
      {"underline", "Κάτω από"},
      {"underline_message", "Κείμενο με υπογράμμιση"},
      {"inc_font_message", "Αύξηση μεγέθους γραμματοσειράς"},
      {"dec_font_message", "Μείωση μεγέθους γραμματοσειράς"},
      {"image", "Εικόνα"},
      {"image_message", "Εισαγωγή εικόνας"},
      {"untitled", "Χωρίς τίτλο"},
      {"statistic", "Στατιστικά"},
      {"statistic_message_1", "Γραμμές: {0}"},
      {"statistic_message_2", "Λέξεις: {0}"},
      {"statistic_message_3", "Χαρακτήρες: {0}"},
      {"statistic_message_4", "Σελίδες: {0}"},
      {"analysis", "Ανάλυση"},
      {"analysis_message_1", "Μέσος όρος Λέξεων: {0}"},
      {"analysis_message_2", "Μέσος όρος Γραμμών: {0}"},
      {"analysis_message_3", "Κεφαλαία: {0}"},
      {"analysis_message_4", "Μικρά: {0}"},
      {"analysis_message_5", "Γλώσσα: {0}"},
      {"exit_message", "Είστε σίγουροι ότι θέλετε να εξέλθετε;"},
      {"login_success", "Η σύνδεση ήταν επιτυχής, ανακατευθύνετε..."},
      {"error", "Σφάλμα"},
      {"fill_all", "Παρακαλώ συμπληρώστε όλα τα πεδία."},
      {"register_success", "Η εγγραφή ήταν επιτυχής, παρακαλώ συνδεθείτε."},
      {"already_registered", "Ήδη εγγεγραμμένος"},
      {"email", "Ηλεκτρονικό ταχυδρομείο"},
      {"password", "Κωδικός πρόσβασης"},
      {"login", "Σύνδεση"},
      {"register", "Εγγραφή"},
      {"powersaver", "Εξοικονόμηση ενέργειας"},
      {"readonly", " — Μόνο για ανάγνωση"}}},
    {"1037",
     {{"new", "חדש"},
      {"open", "פתח"},
      {"save", "שמור"},
      {"save_as", "שמור בשם"},
      {"print", "הדפס"},
      {"exit", "יציאה"},
      {"file", "קובץ"},
      {"interface", "ממשק"},
      {"ui", "ממשק משתמש"},
      {"format", "פורמט"},
      {"alignment", "יישור"},
      {"color", "צבע"},
      {"multimedia", "מדיה מרובת"},
      {"darklight", "כהה/בהיר"},
      {"darklight_message", "שנה ערכת נושא"},
      {"edit", "עריכה"},
      {"view", "תצוגה"},
      {"viewmode", "מצב תצוגה"},
      {"viewmode_message", "שנה את מצב התצוגה"},
      {"help", "עזרה"},
      {"help_message", "עזרה"},
      {"help_shortcut", "קיצורי דרך"},
      {"help_description", "תיאור"},
      {"about", "על"},
      {"new_message", "מסמך חדש"},
      {"open_message", "פתח מסמך"},
      {"save_message", "שמור מסמך"},
      {"save_as_message", "שמור מסמך בשם"},
      {"print_message", "הדפס מסמך"},
      {"find", "חפש"},
      {"find_message", "חפש טקסט"},
      {"replace", "החלף"},
      {"replace_message", "החלף טקסט"},
      {"undo", "בטל"},
      {"undo_message", "ביטול פעולה"},
      {"redo", "שחזר"},
      {"redo_message", "שחזור פעולה"},
      {"right", "ימין"},
      {"right_message", "יישור טקסט לימין"},
      {"center", "מרכז"},
      {"center_message", "יישור טקסט למרכז"},
      {"left", "שמאל"},
      {"left_message", "יישור טקסט לשמאל"},
      {"justify", "מלא"},
      {"justify_message", "יישור טקסט מלא"},
      {"font", "גופן"},
      {"font_message", "שנה גופן"},
      {"font_size", "גודל גופן"},
      {"font_size_message", "שנה גודל גופן"},
      {"font_color", "צבע גופן"},
      {"font_color_message", "שנה צבע גופן"},
      {"contentBackgroundColor", "צבע רקע"},
      {"contentBackgroundColor_message", "שנה צבע רקע"},
      {"bold", "מודגש"},
      {"bold_message", "טקסט מודגש"},
      {"italic", "נטוי"},
      {"italic_message", "טקסט נטוי"},
      {"underline", "קו תחתון"},
      {"underline_message", "טקסט תחת קו"},
      {"inc_font_message", "הגדל גודל גופן"},
      {"dec_font_message", "הקטן גודל גופן"},
      {"image", "תמונה"},
      {"image_message", "הוסף תמונה"},
      {"untitled", "ללא כותרת"},
      {"statistic", "סטטיסטיקה"},
      {"statistic_message_1", "שורות: {0}"},
      {"statistic_message_2", "מילים: {0}"},
      {"statistic_message_3", "תווים: {0}"},
      {"statistic_message_4", "דפים: {0}"},
      {"analysis", "ניתוח"},
      {"analysis_message_1", "ממוצע מילים: {0}"},
      {"analysis_message_2", "ממוצע שורות: {0}"},
      {"analysis_message_3", "אותיות רישיות: {0}"},
      {"analysis_message_4", "אותיות קטנות: {0}"},
      {"analysis_message_5", "שפה: {0}"},
      {"exit_message", "האם אתה בטוח שברצונך לצאת?"},
      {"login_success", "ההתחברות בוצעה בהצלחה, מעביר..."},
      {"error", "שגיאה"},
      {"fill_all", "אנא מלא את כל השדות."},
      {"register_success", "הרישום בוצע בהצלחה, אנא היכנס."},
      {"already_registered", "כבר רשום"},
      {"email", "אימייל"},
      {"password", "סיסמה"},
      {"login", "התחבר"},
      {"register", "הירשם"},
      {"powersaver", "חיסכון באנרגיה"},
      {"readonly", " — לקריאה בלבד"}}},
};

extern const int languages_size;

const char *get_language_by_lcid(const QString &lcid);

const char *get_locale(void);

#endif // GLOBALS_H
